[WIP] Chap3 by oka
Andolab/NLP100_2019 pull request #9
Opened 2019-04-11 12:25 UTC by YujiOka

- [ ] 20
- [ ] 21
- [ ] 22
- [ ] 23
- [ ] 24
- [ ] 25
- [ ] 26
- [ ] 27
- [ ] 28
- [ ] 29

2019-05-07 00:48 UTC, rikeda71 requested changes
レビューしました．
おおよそいいと思います．
24だけ，答えが違うと思うので直してください．
ほんの少し正規表現が足りません．

2019-05-07 00:48 UTC, s14t284 commented on oka/chap3/knock20.py
> +            print(data_json["text"])
8~13行目，関数として定義して，各問題で使いまわしていいからね．

2019-05-07 00:48 UTC, s14t284 commented on oka/chap3/knock24.py
> +    match = re.match(r"ファイル:(?P<content>(.+?))\|", lines)
足りない気がする．．．
俺が解いた時の答えは以下になりました．
```
Royal Coat of Arms of the United Kingdom.svg
Battle of Waterloo 1815.PNG
The British Empire.png
Uk topo en.jpg
BenNevis2005.jpg
Elizabeth II greets NASA GSFC employees, May 8, 2007 edit.jpg
Palace of Westminster, London - Feb 2007.jpg
David Cameron and Barack Obama at the G20 Summit in Toronto.jpg
Soldiers Trooping the Colour, 16th June 2007.jpg
Scotland Parliament Holyrood.jpg
London.bankofengland.arp.jpg
City of London skyline from London City Hall - Oct 2008.jpg
Oil platform in the North SeaPros.jpg
Eurostar at St Pancras Jan 2008.jpg
Heathrow T5.jpg
Anglospeak.svg
CHANDOS3.jpg
The Fabs.JPG
PalaceOfWestminsterAtNight.jpg
Westminster Abbey - West Door.jpg
Edinburgh Cockburn St dsc06789.jpg
Canterbury Cathedral - Portal Nave Cross-spire.jpeg
Kew Gardens Palm House, London - July 2009.jpg
2005-06-27 - United Kingdom - England - London - Greenwich.jpg
Stonehenge2007 07 30.jpg
Yard2.jpg
Durham Kathedrale Nahaufnahme.jpg
Roman Baths in Bath Spa, England - July 2006.jpg
Fountains Abbey view02 2005-08-27.jpg
Blenheim Palace IMG 3673.JPG
Liverpool Pier Head by night.jpg
Hadrian's Wall view near Greenhead.jpg
London Tower (1).JPG
Wembley Stadium, illuminated.jpg
```

2019-05-07 00:48 UTC, s14t284 commented on oka/chap3/knock29.py
> +    return re.sub(r"\'{2,5}", "", text2)
こんな感じで，正規表現が複数回出現すると何が何の処理なのかわからなくなるので，
自分の研究で正規表現を使った処理を書く時は，`re.compile()`を使って，正規表現自体に変数名を持たせることで，可読性が上げましょう．（今回はこのままでOK）
参考：https://docs.python.org/ja/3/library/re.html#re.compile

2019-05-08 07:57 UTC, rikeda71 approved these changes

2019-05-08 08:17 UTC, sekishin reviewed
ok

2019-05-08 08:18 UTC, merged